name: Main

on:
  push:
    branches:
      - master
    tags:
      - v*

  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      skip-test:
        description: 'Skip test'
        type: choice
        required: true
        default: 'false'
        options:
          - "true"
          - "false"

jobs:
  check:
    uses: kestra-io/actions/.github/workflows/plugins.yml@main
    with:
      skip-test: ${{ github.event.inputs.skip-test == 'true' }}
      gradle-publish: false
    secrets: inherit
